### PR TITLE
Document environment variables from dockerfile

### PR DESCRIPTION
**Pull request by MartinMuzatko**

### CODE REVIEW

**Comment by lauriejim** [comment]
Hello! Can you write a comment about what and why you did that please.

**Comment by MartinMuzatko** [comment]
Hello @lauriejim.

The Dockerfile is the first thing you examine when setting up a container.
by setting the ENV variables in the Dockerfile instead of the [strapi.sh](https://github.com/strapi/strapi-docker/blob/master/strapi.sh#L14-L19) file, you get self-documenting environment variables.

1. ENV vars are visible in the Dockerfile
2. ENV vars are visible with `docker inspect`
3. ENV vars are listed as definable, even without being set per user, or being documented via a README.md file:
image

**Comment by lauriejim** [comment]
Okay 

Here is travis issue.

```
$ docker build -t strapi/strapi .
Sending build context to Docker daemon  8.192kB
Error response from daemon: ENV must have two arguments
The command "docker build -t strapi/strapi ." exited with 1.
```

I think it's for database username and password

**Comment by alexandrebodin** [comment]
HI, 

We just released a full rebuild of our docker image 🎉 
We are closing the issues and open PRs to start fresh.

If you feel like something is missing or want to add things feel free to open new PRs ! 💯

**Pull request closed without merging**
